#!/usr/bin/env bash

yarn install
yarn build
rice embed-go
gcloud config configurations activate join-react-test
gcloud config set project join-com-test
gcloud app deploy --quiet --project join-com-test